# Generated by Django 5.2 on 2025-04-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
