# Generated by Django 5.2 on 2025-04-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0003_escola_alter_user_user_type_user_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='escola',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
