# Generated by Django 5.2 on 2025-04-28 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0005_aluno_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rm',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CoordenadorVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacao', models.CharField(max_length=6)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_ate', models.DateTimeField()),
                ('coordenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
