# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0006_aluno_rm_coordenadorverificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='email_pessoal_institucional',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email institucional do coordenador'),
        ),
    ]
