# Generated by Django 5.2 on 2025-05-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0007_coordenador_email_pessoal_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email institucional da escola'),
        ),
    ]
