# Generated by Django 5.2 on 2025-05-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0008_escola_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(default='Aluno Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenador',
            name='nome_completo',
            field=models.CharField(default='Aluno Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rm',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email_pessoal_institucional',
            field=models.EmailField(default='Aluno Padrão', max_length=255, unique=True, verbose_name='Email institucional do coordenador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordenadorverificacao',
            name='coordenador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diverge.coordenador'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='diverge.aluno'),
        ),
    ]
