# Generated by Django 5.2 on 2025-05-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0009_aluno_nome_completo_coordenador_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
