# Generated by Django 5.2 on 2025-05-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0010_alter_coordenador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='diverge.escola'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rm',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Aluno'), ('COORDINATOR', 'Coordenador'), ('SUPERADMIN', 'Administrador do Sistema'), ('ESCOLA', 'Escola')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
