# Generated by Django 5.2 on 2025-05-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0013_user_nome_alter_user_email_alter_user_escola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome_completo',
        ),
    ]
