# Generated by Django 5.2 on 2025-05-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0014_remove_aluno_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diverge.coordenador'),
        ),
    ]
