# Generated by Django 5.2 on 2025-05-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0015_aluno_coordenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='nome_completo',
        ),
    ]
