# Generated by Django 5.2 on 2025-05-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0016_remove_coordenador_nome_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='rm',
            new_name='ra',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rm',
            new_name='ra',
        ),
    ]
