# Generated by Django 5.2 on 2025-05-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0017_alter_coordenador_options_rename_rm_aluno_ra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='escola',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diverge.escola'),
        ),
    ]
