# Generated by Django 5.2 on 2025-05-10 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0018_alter_user_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diverge.escola'),
        ),
    ]
