# Generated by Django 5.2 on 2025-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0019_alter_user_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='email_pessoal_institucional',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(default='email@escola.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
