# Generated by Django 5.2 on 2025-05-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0020_remove_aluno_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diverge.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenador',
            name='escola',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='diverge.escola'),
            preserve_default=False,
        ),
    ]
