# Generated by Django 5.2 on 2025-05-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverge', '0021_aluno_escola_coordenador_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
